import test from 'node:test';
import assert from 'node:assert/strict';
import baseline from '../src/content-pack.json' with {type:'json'};
import {applyContentPack,pack} from '../src/content-pack.js';
import {pathTo,validateDoc} from '../src/model.js';
const original=()=>({version:1,theme:'purple',nodes:structuredClone(baseline.nodes),links:[],contentPacks:[baseline.id]});
test('lower review preserves every upper node, personal images and descriptions',()=>{const d=original();let upperIds=new Set(d.nodes.filter(n=>pathTo(d,n.id).some(p=>p.id==='upper')).map(n=>n.id));d.nodes.find(n=>n.id==='basic::백 익스텐션').images=[{id:'mine',url:'https://example.com/mine.jpg'}];d.nodes.find(n=>n.id==='basic::백 익스텐션').fields=[{id:'own',title:'내 설명',body:'보존',visible:true}];const next=applyContentPack(d);assert.notEqual(pack.id,baseline.id);assert.deepEqual(next.nodes.filter(n=>upperIds.has(n.id)).map(({englishName,...n})=>n),d.nodes.filter(n=>upperIds.has(n.id)));assert.equal(next.nodes.find(n=>n.id==='basic::백 익스텐션').images[0].id,'mine');assert(next.nodes.find(n=>n.id==='basic::백 익스텐션').fields.some(f=>f.body==='보존'));validateDoc(next)});
test('corrects forms, avoids categorical compound classification for hip-dominant variants',()=>{const d=applyContentPack(original());assert(pathTo(d,'basic::힙 쓰러스트').some(n=>n.label==='등 상부 지지'));assert(pathTo(d,'basic::글루트 브리지').some(n=>n.label==='바닥 지지'));assert(pathTo(d,'basic::백 익스텐션').some(n=>n.label==='고관절 중심'));assert(!pathTo(d,'basic::핵 스쿼트').some(n=>n.label==='수직'));assert.equal(d.nodes.find(n=>n.id==='lunge').label,'런지·편측 계열');assert.equal(d.nodes.find(n=>n.id==='basic::커시 런지').label,'커트시 런지')});
test('merges out-thigh alias without losing attachments, adds calf raises and is idempotent',()=>{const d=original();d.nodes.find(n=>n.id==='basic::아웃 타이').images=[{id:'out-photo',url:'https://example.com/out.jpg'}];d.nodes.find(n=>n.id==='basic::아웃 타이').fields=[{id:'out-note',title:'메모',body:'기존 메모',visible:false}];const next=applyContentPack(d);assert(!next.nodes.some(n=>n.id==='basic::아웃 타이'));assert(next.nodes.find(n=>n.id==='basic::힙 어브덕션').images.some(i=>i.id==='out-photo'));assert(next.nodes.find(n=>n.id==='basic::힙 어브덕션').fields.some(f=>f.body==='기존 메모'));assert.equal(next.nodes.filter(n=>n.level==='basic'&&n.label.includes('카프 레이즈')).length,2);assert.deepEqual(applyContentPack(next),next);validateDoc(next)});
