import React,{useState,useEffect,useMemo,useRef,useCallback} from 'react';
import {createRoot} from 'react-dom/client';
import {ReactFlow,ReactFlowProvider,Handle,Position,Controls,Background,useReactFlow} from '@xyflow/react';
import {useDocument} from '../useDocument';
import {pathTo,themes} from '../model';
import {TEST_KEY,criteriaFor,record,progress,stats,setCheck,linkCriterion,unlinkCriterion,deleteCriterion,removeMember} from './model';
import '@xyflow/react/dist/style.css';
import './style.css';
import offlineSeed from './offline-seed.json';
import {questLayout} from './layout';
const date=v=>v?new Date(v).toLocaleDateString('ko-KR'):'—';
function Card({data:d}){const ref=useRef(null);useEffect(()=>{const observer=new ResizeObserver(()=>d.measure(d.id,Math.ceil(ref.current.offsetHeight)));observer.observe(ref.current);return()=>observer.disconnect()},[d.id,d.measure]);return <div ref={ref} className={'tree-card '+(d.hasQuest?'has-quest ':'')+(d.done?'achieved ':'')+(d.selected?'selected ':'')+(d.hasImage?'has-image ':'')+(d.englishName?.trim()?'has-english':'')}>
 <Handle type="target" position={Position.Top}/>
 {d.hasQuest&&<button className="quest-rail nodrag nopan" aria-label={d.label+' 퀘스트 보기'} onClick={e=>{e.stopPropagation();d.openQuest(d.id)}}><span className="shield">{d.done?'✓':'◆'}</span><strong>QUEST</strong><span>{d.done?'달성':d.checked?'진행 중':'도전 전'}</span><b>{d.checked}/{d.total}</b></button>}<div className="card-content">
 <div className="card-top"><span>{!d.parent?'시작하기':d.kind==='exercise'?'EXERCISE':'MOVEMENT'}</span><span>{d.hasQuest?'◆':'⑂'}</span></div>
 {d.hasImage&&<img className="card-photo" src={d.images[0].url} alt="" loading="lazy"/>}
 <h3>{d.label}</h3>{d.englishName?.trim()&&<div className="card-english">{d.englishName}</div>}
 <div className="card-bottom"><span>{d.hasQuest&&d.done?date(d.achievedAt):d.count?d.count+'개의 가지':'자세히 보기'}</span>{d.count>0&&<button className="nodrag" aria-label={d.label+' '+(d.open?'접기':'펼치기')} onClick={e=>{e.stopPropagation();d.toggle(d.id)}}>{d.open?'−':'＋'}</button>}</div>
 </div><Handle type="source" position={Position.Bottom}/>
 </div>}
const nodeTypes={movement:Card};
function Modal({title,close,children}){const ref=useRef(null);useEffect(()=>{const previous=document.activeElement;ref.current?.querySelector('button')?.focus();const key=e=>{if(e.key==='Escape'){e.stopPropagation();close()}if(e.key==='Tab'){const elements=ref.current?.querySelectorAll('button:not(:disabled),input,select,textarea,a[href]');if(!elements?.length)return;const first=elements[0],last=elements[elements.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}}};document.addEventListener('keydown',key);return()=>{document.removeEventListener('keydown',key);previous?.focus()}},[]);return <div className="modal-backdrop" onClick={close}><section ref={ref} role="dialog" aria-modal="true" aria-label={title} className="modal" onClick={e=>e.stopPropagation()}><div className="modal-head"><h2>{title}</h2><button aria-label="닫기" onClick={close}>×</button></div>{children}</section></div>}
function AssessmentManager({q,change,close}){
 const [image,setImage]=useState(''),[editing,setEditing]=useState(null),[label,setLabel]=useState(''),[description,setDescription]=useState(''),[search,setSearch]=useState(''),[pending,setPending]=useState(null),[error,setError]=useState('');
 function choose(c){setImage(c?.image||'');setEditing(c?.id||'new');setLabel(c?.label||'');setDescription(c?.description||'');setError('');}
 function save(){if(image&&!/^https?:\/\//i.test(image.trim())){setError('이미지는 http 또는 https 주소를 입력해 주세요.');return}if(!label.trim()){setError('평가 항목 이름을 입력해 주세요.');return}change(q=>{if(editing==='new')q.library.push({id:crypto.randomUUID(),label:label.trim(),description:description.trim(),image:image.trim()});else Object.assign(q.library.find(c=>c.id===editing),{label:label.trim(),description:description.trim(),image:image.trim()})});setEditing(null);}
 return <Modal title="평가 항목 관리" close={close}><div className="modal-body"><p className="hint">여기서 등록한 조건을 각 가지의 드롭다운에서 선택합니다. 문구 수정은 연결된 모든 가지에 반영되고, 기존 달성 기록은 유지됩니다.</p><div className="manager-tools"><input aria-label="평가 항목 검색" placeholder="평가 항목 검색" value={search} onChange={e=>setSearch(e.target.value)}/><button className="primary" onClick={()=>choose(null)}>＋ 항목 추가</button></div>
 {editing&&<form className="editor" onSubmit={e=>{e.preventDefault();save()}}><label>평가 항목<input autoFocus aria-label="평가 항목 이름" maxLength={200} value={label} onChange={e=>setLabel(e.target.value)} placeholder="예: 팔 형태를 유지하며 동작한다"/></label><label>설명 (선택)<textarea aria-label="평가 항목 설명" value={description} onChange={e=>setDescription(e.target.value)} maxLength={1000}/></label><label>안내 이미지 주소 (선택)<input aria-label="안내 이미지 주소" type="url" placeholder="https://…" value={image} onChange={e=>setImage(e.target.value)}/></label>{error&&<p role="alert">{error}</p>}<div className="editor-actions"><button type="button" onClick={()=>setEditing(null)}>취소</button><button className="primary" disabled={!label.trim()}>항목 저장</button></div></form>}
 <div className="library-list">{q.library.filter(c=>(c.label+' '+c.description).includes(search)).map(c=>{const uses=Object.values(q.bindings).filter(ids=>ids.includes(c.id)).length;return <article key={c.id}><div><b>{c.label}</b>{c.description&&<p>{c.description}</p>}<small>{uses}개 가지에 연결</small></div><button onClick={()=>choose(c)}>수정</button><button className="danger" onClick={()=>setPending(c)}>삭제</button></article>})}</div>
 {!q.library.length&&<p className="empty">아직 평가 항목이 없습니다. 첫 항목을 추가해 주세요.</p>}
 {pending&&<div className="confirm" role="alert"><b>‘{pending.label}’ 항목을 삭제할까요?</b><p>연결된 {Object.values(q.bindings).filter(ids=>ids.includes(pending.id)).length}개 가지에서 이 조건도 해제됩니다. 다른 조건은 유지됩니다.</p><button onClick={()=>setPending(null)}>취소</button><button className="danger" onClick={()=>{change(q=>deleteCriterion(q,pending.id));if(editing===pending.id)setEditing(null);setPending(null)}}>평가 항목 삭제</button></div>}
 </div></Modal>
}
function LearnerManager({q,change,selected,onSelected,close}){
 const [edit,setEdit]=useState(null),[name,setName]=useState(''),[pending,setPending]=useState(null);
 return <Modal title="학습자 관리" close={close}><div className="modal-body"><p className="hint">테스트용 이름으로 사용해 보세요. 학습자별 체크와 달성일은 따로 저장됩니다.</p><button className="primary" onClick={()=>{setEdit('new');setName('')}}>＋ 학습자 추가</button>
 {edit&&<form className="editor" onSubmit={e=>{e.preventDefault();if(!name.trim())return;const id=edit==='new'?crypto.randomUUID():edit;change(q=>{if(edit==='new')q.members.push({id,name:name.trim(),records:{}});else q.members.find(m=>m.id===edit).name=name.trim()});if(edit==='new')onSelected(id);setEdit(null)}}><label>이름<input autoFocus aria-label="학습자 이름" maxLength={40} value={name} onChange={e=>setName(e.target.value)}/></label><div className="editor-actions"><button type="button" onClick={()=>setEdit(null)}>취소</button><button className="primary" disabled={!name.trim()}>학습자 저장</button></div></form>}
 <div className="library-list">{q.members.map(m=><article key={m.id}><div><b>{m.name}</b><small>{stats(q,m).done} / {stats(q,m).total} 가지 달성{selected===m.id?' · 선택 중':''}</small></div><button onClick={()=>{setEdit(m.id);setName(m.name)}}>수정</button><button className="danger" disabled={q.members.length<=1} onClick={()=>setPending(m)}>삭제</button></article>)}</div>
 <p className="hint">학습자는 최소 1명 유지합니다.</p>{pending&&<div className="confirm" role="alert"><b>{pending.name} 학습자를 삭제할까요?</b><p>이 학습자의 테스트 달성 기록도 삭제됩니다.</p><button onClick={()=>setPending(null)}>취소</button><button className="danger" onClick={()=>{const next=q.members.find(m=>m.id!==pending.id);change(q=>removeMember(q,pending.id));if(selected===pending.id)onSelected(next.id);if(edit===pending.id)setEdit(null);setPending(null)}}>학습자 삭제</button></div>}
 </div></Modal>
}
function App({sync,openOffline}){
 const {doc,replace}=sync;const q=doc.quest?.schema===2?doc.quest:null;
 const [memberId,setMemberId]=useState('demo-a'),[selected,setSelected]=useState(null),[expanded,setExpanded]=useState(new Set(['upper','lower'])),[modal,setModal]=useState(null),[choice,setChoice]=useState(''),[search,setSearch]=useState(''),[message,setMessage]=useState(''),[showPanel,setShowPanel]=useState(true),[pendingUnlink,setPendingUnlink]=useState(null);
 const [panelMode,setPanelMode]=useState('info'),[viewCriterion,setViewCriterion]=useState(null),[heights,setHeights]=useState({});
 const measure=useCallback((id,height)=>setHeights(prev=>prev[id]===height?prev:{...prev,[id]:height}),[]);
 const panelRef=useRef(null);
 const flow=useReactFlow(),focusRef=useRef(null),latest=useRef(doc);latest.current=doc;
 const member=q?.members.find(m=>m.id===memberId)||q?.members[0],node=doc.nodes.find(n=>n.id===selected),disabled=!!sync.conflict||!q;
 function change(fn){if(disabled)return;const next=structuredClone(latest.current);try{fn(next.quest);latest.current=next;replace(next)}catch(e){setMessage(e.message)}}
 const toggle=id=>setExpanded(prev=>{const next=new Set(prev);next.has(id)?next.delete(id):next.add(id);return next});
 function select(id,reveal=false,mode='info'){setPanelMode(mode);setSelected(id);setChoice('');setPendingUnlink(null);setShowPanel(true);if(reveal)setExpanded(prev=>new Set([...prev,...pathTo(doc,id).slice(0,-1).map(n=>n.id)]));else if(doc.nodes.some(n=>n.parent===id))setExpanded(prev=>new Set([...prev,id]));focusRef.current=id;}
 useEffect(()=>{if(!q)return;const timer=setTimeout(()=>{const id=focusRef.current;focusRef.current=null;if(id)flow.fitView({nodes:[{id}],duration:300,padding:.8,maxZoom:1,minZoom:.015});else flow.fitView({duration:300,padding:.18,maxZoom:1});},120);return()=>clearTimeout(timer)},[expanded,showPanel,selected,!!q,heights]);
 useEffect(()=>{if(panelRef.current)panelRef.current.scrollTop=0;},[selected,showPanel,panelMode]);
 useEffect(()=>{if(!message)return;const t=setTimeout(()=>setMessage(''),3500);return()=>clearTimeout(t)},[message]);
 useEffect(()=>{let timer;const resize=()=>{clearTimeout(timer);timer=setTimeout(()=>flow.fitView({duration:250,padding:.18,maxZoom:1}),180)};window.addEventListener('resize',resize);return()=>{clearTimeout(timer);window.removeEventListener('resize',resize)}},[flow]);
 const laid=useMemo(()=>q?questLayout(doc,expanded,heights):[],[doc,expanded,!!q,heights]);
 const nodes=laid.map(n=>{const pr=progress(q,member,n.id);return {id:n.id,type:'movement',position:n.position,data:{...n,...pr,measure,openQuest:id=>select(id,false,'quest'),hasQuest:pr.total>0,hasImage:n.show?.image!==false&&n.images.length>0,selected:n.id===selected,count:doc.nodes.filter(x=>x.parent===n.id).length,open:expanded.has(n.id),toggle,achievedAt:record(member,n.id).achievedAt}}});
 const visible=new Set(nodes.map(n=>n.id));
 const edges=laid.filter(n=>n.parent&&visible.has(n.parent)).map(n=>({id:'parent-'+n.id,source:n.parent,target:n.id,type:'smoothstep',style:{stroke:'#cbb7e0',strokeWidth:1.6}})).concat(doc.links.filter(l=>visible.has(l.source)&&visible.has(l.target)).map((l,i)=>({...l,id:'related-'+i,type:'smoothstep',style:{stroke:'#b4a5c4',strokeDasharray:'5 5'}})));
 if(!sync.ready)return <div className="loading">테스트 트리를 불러오는 중…</div>;
 if(!q)return <div className="loading"><h2>클라우드 연결을 완료하지 못했습니다.</h2><p>서버 응답이 지연되고 있습니다. 기기 테스트는 클라우드와 별도로 저장됩니다.</p><button onClick={sync.refresh}>연결 확인</button> <button className="primary" onClick={openOffline}>기기 테스트로 열기</button></div>;
 const summary=stats(q,member),items=selected?criteriaFor(q,selected):[],r=record(member,selected),pr=selected?progress(q,member,selected):{total:0,checked:0,done:false},quests=doc.nodes.filter(n=>criteriaFor(q,n.id).length),available=q.library.filter(c=>!items.some(i=>i.id===c.id));
 const results=search.trim()?doc.nodes.filter(n=>(n.label+' '+(n.englishName||'')).toLowerCase().includes(search.trim().toLowerCase())).slice(0,25):[];
 return <div className="quest-app" style={{'--accent':themes[doc.theme]?.color||'#8050ae'}}>
 <header><div className="brand"><span className="brand-icon">⑂</span><div><b>MOVEMENT ATLAS</b><small>기존 움직임 지도에, 나만의 성장 기록</small></div><span className="test-badge">퀘스트 테스트</span></div><div className="header-right"><span className="sync" role="status">{({preview:'기기 테스트 · 클라우드 미연결',saved:'클라우드 저장됨',pending:'저장 대기',saving:'저장 중',offline:'기기에 보관 · 연결 필요',conflict:'저장 충돌',setup:'연결 설정 필요'})[sync.status]||'연결 중'}</span><button onClick={()=>{sync.refresh();setMessage('클라우드 연결을 확인하고 있습니다.')}}>연결 확인</button><a href="./index.html#tree=27ce43fa-489c-4367-b6ff-891b478abe3e">기존 트리 ↗</a></div></header>
 <div className="test-notice">{sync.status==='preview'?'기기 테스트 모드 · 변경은 이 브라우저에만 저장됩니다. 다른 기기와 동기화되지 않으며 클라우드에 자동 반영하지 않습니다.':'원본 트리를 복사한 독립 테스트판입니다. 가지 구조를 바꾸지 않고, 원하는 가지에만 퀘스트를 연결합니다.'}</div>
 {sync.conflict&&<div className="conflict">다른 기기에서 변경했습니다. <button onClick={()=>sync.resolve('remote')}>클라우드 저장본 사용</button><button onClick={()=>sync.resolve('local')}>내 변경으로 저장</button></div>}
 {sync.error&&<div className="conflict">{sync.error}</div>}
 <section className="dashboard"><div className="member"><label htmlFor="learner">학습자</label><select id="learner" value={member.id} onChange={e=>setMemberId(e.target.value)}>{q.members.map(m=><option key={m.id} value={m.id}>{m.name}</option>)}</select><button onClick={()=>setModal('learners')} disabled={disabled}>학습자 관리</button></div><div className="progress"><div><span>퀘스트 달성률</span><b>{summary.percent}<small>%</small></b></div><div className="progress-track"><i style={{width:summary.percent+'%'}}/></div><small>{summary.done} / {summary.total}개 가지 달성</small></div><div className="dashboard-actions"><button onClick={()=>setModal('quests')}>◆ 퀘스트 목록 {quests.length}</button><button className="primary" onClick={()=>setModal('assessments')} disabled={disabled}>평가 항목 관리</button></div></section>
 <nav><div className="search"><input aria-label="트리 검색" placeholder="가지·운동 찾기" value={search} onChange={e=>setSearch(e.target.value)}/>{search&&<div className="search-results">{results.map(n=><button key={n.id} onClick={()=>{select(n.id,true);setSearch('')}}>{n.label}<small>{pathTo(doc,n.id).slice(0,-1).map(p=>p.label).join(' › ')}</small></button>)}{!results.length&&<p>검색 결과가 없습니다.</p>}</div>}</div><button onClick={()=>{focusRef.current=null;setExpanded(new Set(doc.nodes.map(n=>n.id)))}}>모두 펼치기</button><button onClick={()=>{focusRef.current=null;setExpanded(new Set())}}>모두 접기</button><button onClick={()=>flow.fitView({duration:300,padding:.18,maxZoom:1})}>전체 맞춤</button><span className="legend"><i/> 일반 가지 <b>◆</b> 퀘스트 가지 <em>✓</em> 달성</span>{!showPanel&&<button onClick={()=>setShowPanel(true)}>상세 열기</button>}</nav>
 <main><div className="map"><ReactFlow nodes={nodes} edges={edges} nodeTypes={nodeTypes} onNodeClick={(_,n)=>select(n.id)} nodesDraggable={false} nodesConnectable={false} fitView minZoom={.015} maxZoom={1.8}><Background color="#e8e7ef" gap={22}/><Controls showInteractive={false}/></ReactFlow><div className="map-note">카드 → 가지 정보 · QUEST → 달성 조건 · 두 손가락 확대/축소</div></div>
 {showPanel&&<aside><div className="panel-header"><div><span className="eyebrow">{panelMode==='quest'?'QUEST':'MOVEMENT'}</span><h2>{node?.label||'가지에 퀘스트를 붙여보세요'}</h2>{node?.englishName&&<small>{node.englishName}</small>}</div><button aria-label="상세 닫기" onClick={()=>setShowPanel(false)}>×</button></div>
 <div className="panel-body" ref={panelRef}>{node?<>{node.show?.path!==false&&<div className="breadcrumbs">{pathTo(doc,node.id).map(n=><button key={n.id} onClick={()=>select(n.id,true)}>{n.label}</button>)}</div>}
 {panelMode==='info'?<section className="branch-info">
 {node.show?.image!==false&&node.images.map((im,i)=><figure key={im.id||i}><img src={im.url} alt={im.caption||node.label} loading="lazy"/>{im.caption&&<figcaption>{im.caption}</figcaption>}</figure>)}
 {node.show?.meanings!==false&&node.meanings.length>0&&<><h3>운동 이름 풀이</h3>{node.meanings.map((m,i)=><div className="meaning" key={m.id||i}><b>{m.word}</b><span>{m.meaning}</span></div>)}</>}
 {node.fields.filter(f=>f.visible!==false&&f.body?.trim()).map((f,i)=><section key={f.id||i}><h3>{f.title}</h3><p>{f.body}</p></section>)}
 <button className="primary full" onClick={()=>setPanelMode('quest')}>{items.length?'◆ 퀘스트 보기':'＋ 퀘스트 추가'}</button>
 </section>:<><button className="text-button" onClick={()=>setPanelMode('info')}>← 가지 정보 보기</button>
 {items.length>0?<><div className="quest-summary"><span className={'status-pill '+(pr.done?'done':'')}>{pr.done?'✓ 달성':pr.checked?'◈ 진행 중':'◇ 도전 전'}</span><small>{member.name} · {pr.checked}/{pr.total} 조건 완료</small></div><h3>달성 조건</h3><div className="criteria">{items.map(c=><div className="criterion" key={c.id}><label><input type="checkbox" aria-label={c.label} checked={!!r.checks?.[c.id]?.done} disabled={disabled} onChange={e=>{change(q=>setCheck(q,member.id,node.id,c.id,e.target.checked));if(e.target.checked)setMessage('✦ 조건 달성! 성장 기록에 반영했습니다.')}}/><span>{c.label}{c.description&&<small>{c.description}</small>}</span></label><button aria-label={c.label+' 보기'} onClick={()=>setViewCriterion(c)}>보기</button><button aria-label={c.label+' 연결 해제'} disabled={disabled} onClick={()=>setPendingUnlink(c)}>해제</button></div>)}</div><div className="date-grid"><div>달성일<strong>{date(r.achievedAt)}</strong></div><div>최초 달성일<strong>{date(r.firstAchievedAt)}</strong></div></div></>:<div className="empty-quest"><span>◇</span><p>아직 퀘스트가 없는 가지입니다.</p><small>아래에서 평가 조건을 선택하면<br/>이 가지가 퀘스트로 표시됩니다.</small></div>}
 <section className="attach"><h3>{items.length?'평가 조건 추가':'퀘스트 추가'}</h3><select aria-label="평가 조건 선택" value={choice} onChange={e=>setChoice(e.target.value)} disabled={disabled||!available.length}><option value="">{available.length?'평가 항목을 선택하세요':q.library.length?'모든 평가 항목이 연결되어 있습니다':'평가 항목을 먼저 등록하세요'}</option>{available.map(c=><option key={c.id} value={c.id}>{c.label}</option>)}</select>{choice&&<p className="hint">{q.library.find(c=>c.id===choice)?.description||q.library.find(c=>c.id===choice)?.label}</p>}<button className="primary full" disabled={disabled||!choice} onClick={()=>{change(q=>linkCriterion(q,node.id,choice));setChoice('');setMessage('이 가지에 퀘스트 조건을 연결했습니다.')}}>선택한 조건 연결</button><button className="text-button" disabled={disabled} onClick={()=>setModal('assessments')}>평가 항목 추가·수정은 관리 화면에서 →</button></section>
 {pendingUnlink&&<div className="confirm"><b>이 가지에서 조건을 해제할까요?</b><p>평가 항목은 목록에 남습니다. 이 가지의 학습자별 해당 체크는 해제되며, 변경 이력은 보존됩니다.</p><button onClick={()=>setPendingUnlink(null)}>취소</button><button className="danger" onClick={()=>{change(q=>unlinkCriterion(q,node.id,pendingUnlink.id));setPendingUnlink(null)}}>조건 연결 해제</button></div>}
 {items.length>0&&<label className="memo">학습자별 메모<textarea aria-label="학습자별 메모" value={r.note||''} placeholder="동작에서 확인한 점을 간단히…" disabled={disabled} onChange={e=>change(q=>{const m=q.members.find(m=>m.id===member.id);m.records[node.id]={...record(m,node.id),note:e.target.value}})}/></label>}
 {r.history?.length>0&&<details><summary>변경 이력 {r.history.length}개</summary>{r.history.slice().reverse().map((h,i)=><p key={i}>{date(h.at)} · {h.type==='check'?'달성 체크':h.type==='uncheck'?'체크 해제':'조건 연결 해제'}<br/>{h.label||''}</p>)}</details>}</> }
 </>:<div className="empty-quest"><span>⑂</span><p>기존 트리의 아무 가지나 선택하세요.</p><small>평가 항목을 연결하면 퀘스트가 됩니다.<br/>예시: 밀기 → 단일관절, 힌지</small><button className="full" onClick={()=>setModal('quests')}>예시 퀘스트 보기</button></div>}</div><div className="panel-footer">체크와 변경 사항은 자동 저장됩니다.</div></aside>}
 </main>
 {modal==='assessments'&&!disabled&&<AssessmentManager q={q} change={change} close={()=>setModal(null)}/>}
 {modal==='learners'&&!disabled&&<LearnerManager q={q} change={change} selected={member.id} onSelected={setMemberId} close={()=>setModal(null)}/>}
 {modal==='quests'&&<Modal title="퀘스트가 연결된 가지" close={()=>setModal(null)}><div className="modal-body"><p className="hint">굵은 테두리와 ◆ 배지가 있는 가지입니다. 선택하면 트리의 해당 위치로 이동합니다.</p><div className="quest-list">{quests.map(n=><button key={n.id} onClick={()=>{select(n.id,true,'quest');setModal(null)}}><b>{progress(q,member,n.id).done?'✓':'◆'} {n.label}</b><small>{pathTo(doc,n.id).map(p=>p.label).join(' › ')}</small><span>{progress(q,member,n.id).checked}/{criteriaFor(q,n.id).length} 완료</span></button>)}</div>{!quests.length&&<p>아직 퀘스트가 없습니다. 가지를 선택해 조건을 연결해 주세요.</p>}</div></Modal>}
 {viewCriterion&&<Modal title="달성 조건 보기" close={()=>setViewCriterion(null)}><div className="modal-body condition-preview"><span className="mission-label">◆ MOVEMENT QUEST</span>{viewCriterion.image?<img src={viewCriterion.image} alt="달성 조건 안내" onError={e=>{e.currentTarget.hidden=true}}/>:<div className="condition-placeholder">◇<small>등록된 안내 이미지가 없습니다.</small></div>}<h2>{viewCriterion.label}</h2>{viewCriterion.description&&<p>{viewCriterion.description}</p>}<button className="primary full" onClick={()=>setViewCriterion(null)}>확인</button></div></Modal>}
 {message&&<div className="toast" role="status">{message}</div>}
 </div>
}
const OFFLINE_KEY='movement-quest-local-preview-v2';
function Preview({reconnect}){
 const [doc,setDoc]=useState(()=>{try{const d=JSON.parse(localStorage.getItem(OFFLINE_KEY));if(d?.quest?.schema===2&&Array.isArray(d.nodes))return d;}catch{}return structuredClone(offlineSeed)}),[error,setError]=useState('');
 const replace=d=>{setDoc(d);try{localStorage.setItem(OFFLINE_KEY,JSON.stringify(d));setError('')}catch{setError('기기 저장에 실패했습니다. 이 창을 닫으면 변경 내용이 사라질 수 있습니다.')}};
 return <App sync={{doc,replace,ready:true,status:'preview',refresh:reconnect,error}}/>;
}
function Connected({fallback}){const sync=useDocument(TEST_KEY);useEffect(()=>{if(sync.ready&&sync.status==='offline'&&sync.doc.quest?.schema!==2)fallback()},[sync.ready,sync.status]);return <App sync={sync} openOffline={fallback}/>;}
function Entry(){const [offline,setOffline]=useState(false);return offline?<Preview reconnect={()=>setOffline(false)}/>:<Connected fallback={()=>setOffline(true)}/>;}
createRoot(document.getElementById('root')).render(<ReactFlowProvider><Entry/></ReactFlowProvider>);
