import React,{useState,useEffect,useMemo} from 'react';
import {createRoot} from 'react-dom/client';
import {ReactFlow,ReactFlowProvider,Handle,Position,Controls,Background,useReactFlow} from '@xyflow/react';
import {useDocument} from '../useDocument';
import {TEST_KEY,patterns,record,gate,requirements,status,complete,stats,validPrerequisites} from './model';
import '@xyflow/react/dist/style.css';
import './style.css';
const names={todo:'미도전',active:'도전 중',ready:'확인 대기',done:'달성',review:'재점검',locked:'잠김'};
const marks={todo:'○',active:'◐',ready:'◇',done:'✓',review:'↻',locked:'⌑'};
const date=v=>v?new Date(v).toLocaleDateString('ko-KR'):'아직 없음';
function Card({data:d}){return <div className={'quest-card '+d.state+(d.selected?' selected':'')}><Handle type="target" position={Position.Top}/><div className="card-meta"><span>{d.core?'핵심 움직임':'도구 확장'}</span><span className="state">{marks[d.state]} {names[d.state]}</span></div><h3>{d.label}</h3><small>{d.englishName||'배운 움직임을 내 것으로'}</small>{d.image&&<img src={d.image} alt=""/>}<div className="card-bottom"><span>{d.assigned?'필수 '+d.checked+' / '+d.total:'학습 목표 미배정'}</span><span>{d.state==='done'?date(d.date):d.core?'가지 살펴보기 →':'퀘스트 보기 →'}</span></div><Handle type="source" position={Position.Bottom}/></div>}
const types={quest:Card};
function App(){const sync=useDocument(TEST_KEY),{doc,replace}=sync;const [memberId,setMember]=useState('demo-a'),[filter,setFilter]=useState('all'),[selected,setSelected]=useState('push'),[editing,setEditing]=useState(false),[draft,setDraft]=useState(null),[message,setMessage]=useState(''),[newMember,setNewMember]=useState(''),[showMembers,setShowMembers]=useState(false);const flow=useReactFlow();
 const q=doc.quest,member=q?.members.find(m=>m.id===memberId)||q?.members[0],def=q?.definitions[selected],node=doc.nodes.find(n=>n.id===selected);const rec=member?record(member,selected):{};const disabled=!!sync.conflict||!q;
 const change=fn=>{if(disabled)return;const next=structuredClone(doc);fn(next.quest);replace(next);};
 const patchRecord=patch=>change(q=>{const m=q.members.find(m=>m.id===member.id);m.records[selected]={...record(m,selected),...patch};});
 const select=id=>{setSelected(id);setEditing(false);setDraft(null);if(filter==='all'&&patterns.includes(id))setFilter(id);};
 useEffect(()=>{const t=setTimeout(()=>flow.fitView({padding:.16,duration:350,maxZoom:1}),100);return()=>clearTimeout(t)},[filter,!!q]);
 useEffect(()=>{if(!message)return;const t=setTimeout(()=>setMessage(''),3500);return()=>clearTimeout(t)},[message]);
 const nodes=useMemo(()=>{if(!q||!member)return [];const ids=filter==='all'?patterns:Object.keys(q.definitions).filter(id=>q.definitions[id].pattern===filter);const children=ids.filter(id=>id!==filter);return ids.map((id,i)=>{const n=doc.nodes.find(n=>n.id===id),core=patterns.includes(id),req=requirements(q,member,id),r=record(member,id);return {id,type:'quest',position:filter==='all'?{x:i*280,y:30}:core?{x:Math.max(0,(children.length-1)*140),y:0}:{x:children.indexOf(id)*280,y:230},data:{...n,state:status(q,member,id),selected:id===selected,core,assigned:member.assigned.includes(id),...req,image:core?null:n.images?.[0]?.url,date:r.firstAchievedAt}}})},[doc,memberId,filter,selected]);
 const edges=filter==='all'?[]:nodes.filter(n=>n.id!==filter).map(n=>({id:filter+'-'+n.id,source:filter,target:n.id,type:'smoothstep',style:{stroke:n.data.state==='done'?'#18836a':'#c9c4e6',strokeWidth:2},animated:n.data.state==='active'}));
 if(!sync.ready)return <div className="loading">테스트 트리를 불러오는 중…</div>;
 if(!q)return <div className="loading"><h2>테스트 트리를 불러오지 못했습니다.</h2><button onClick={sync.refresh}>다시 연결</button></div>;
 const summary=stats(q,member),state=def?status(q,member,selected):'todo',req=def?requirements(q,member,selected):{total:0,checked:0},blocked=def?gate(q,member,selected):[];const assigned=member.assigned.includes(selected);const firstBadge=summary.done>=1,coreBadge=patterns.every(id=>record(member,id).status==='done'),expansionBadge=patterns.some(p=>Object.keys(q.definitions).filter(id=>id!==p&&q.definitions[id].pattern===p&&record(member,id).status==='done').length>=2);
 function nextQuest(){const id=member.assigned.find(id=>q.definitions[id]&&!['done','locked'].includes(status(q,member,id)));if(!id){setMessage(summary.done===summary.total&&summary.total>0?'배정된 퀘스트를 모두 달성했습니다!':'도전 가능한 목표가 없습니다. 배정과 선행 조건을 확인해 주세요.');return}setFilter(q.definitions[id].pattern);select(id);}
 function saveDefinition(){const clean={...draft,criteria:draft.criteria.filter(c=>c.label.trim()).map(c=>({...c,label:c.label.trim()}))};if(!clean.criteria.length){setMessage('조건을 1개 이상 입력해 주세요.');return}if(!validPrerequisites(q.definitions,selected,clean.prerequisites)){setMessage('선행 조건이 순환 연결됩니다. 다시 선택해 주세요.');return}change(q=>{q.definitions[selected]=clean;for(const m of q.members){const r=record(m,selected);const counts=requirements(q,m,selected);if(r.status==='done'&&counts.checked!==counts.total)m.records[selected]={...r,status:'review'};}});setEditing(false);setMessage('퀘스트 조건을 저장했습니다.');}
 return <div className="quest-app"><header><div className="brand"><span className="brand-icon">✧</span><div><b>MOVEMENT QUEST</b><small>움직임을 배우고, 새로운 가지를 열다</small></div><span className="test-badge">테스트 트리</span></div><div className="header-right"><span className="sync" role="status">{({saved:'클라우드 저장됨',pending:'저장 대기',saving:'저장 중',offline:'기기에 보관 · 연결 확인 필요',conflict:'다른 기기와 변경 충돌',setup:'연결 설정 필요'})[sync.status]||'연결 중'}</span><button onClick={sync.refresh}>연결 확인</button><a href="./index.html#tree=27ce43fa-489c-4367-b6ff-891b478abe3e">기존 트리 ↗</a></div></header>
 <div className="test-notice">독립 실험 공간 · 기존 운동 트리와 회원 데이터에 영향을 주지 않습니다. 조건과 순서는 코치가 조정하는 예시입니다.</div>
 {sync.conflict&&<div className="conflict">다른 기기에서 수정했습니다. <button onClick={()=>sync.resolve('remote')}>다른 기기 저장본 불러오기</button><button onClick={()=>sync.resolve('local')}>내 변경으로 저장</button></div>}
 {sync.error&&<div className="conflict">{sync.error}</div>}
 <section className="dashboard"><div className="member"><label htmlFor="member">학습자</label><div><select id="member" value={member.id} onChange={e=>{setMember(e.target.value);setEditing(false)}}>{q.members.map(m=><option key={m.id} value={m.id}>{m.name}</option>)}</select><button title="테스트 회원 추가" onClick={()=>setShowMembers(!showMembers)}>＋</button></div>{showMembers&&<form onSubmit={e=>{e.preventDefault();if(!newMember.trim())return;const id=crypto.randomUUID();change(q=>q.members.push({id,name:newMember.trim(),assigned:Object.keys(q.definitions),records:{}}));setMember(id);setNewMember('');setShowMembers(false)}}><input aria-label="새 테스트 회원 이름" value={newMember} onChange={e=>setNewMember(e.target.value)} maxLength={40} placeholder="테스트용 별칭"/><button disabled={disabled||!newMember.trim()}>추가</button></form>}</div><div className="progress"><div><span>나의 학습 달성률</span><b>{summary.percent}<small>%</small></b></div><div className="progress-track"><i style={{width:summary.percent+'%'}}/></div><small>{summary.done} / {summary.total} 퀘스트 달성 · 배정된 목표 기준</small></div><div className="badges"><span className={firstBadge?'earned':''}>✦ 첫 달성</span><span className={expansionBadge?'earned':''}>♧ 움직임 확장</span><span className={coreBadge?'earned':''}>♛ 5대 패턴</span></div><button className="primary next" onClick={nextQuest}>다음 퀘스트 →</button></section>
 <nav><button className={filter==='all'?'active':''} onClick={()=>setFilter('all')}>전체 지도</button>{patterns.map(p=><button key={p} className={filter===p?'active':''} onClick={()=>{setFilter(p);select(p)}}>{doc.nodes.find(n=>n.id===p)?.label} <small>{Object.keys(q.definitions).filter(id=>q.definitions[id].pattern===p&&record(member,id).status==='done').length}/{Object.values(q.definitions).filter(d=>d.pattern===p).length}</small></button>)}<span>미도전 ○ · 도전 중 ◐ · 달성 ✓</span></nav>
 <main><div className="map"><ReactFlow nodes={nodes} edges={edges} nodeTypes={types} onNodeClick={(_,n)=>select(n.id)} nodesDraggable={false} nodesConnectable={false} fitView minZoom={.15} maxZoom={1.7}><Background color="#e8e7ef" gap={22}/><Controls showInteractive={false}/></ReactFlow><div className="map-note">{filter==='all'?'패턴을 누르면 퀘스트가 펼쳐집니다.':'가지는 학습 분류입니다. 선행 조건은 퀘스트별로 설정합니다.'}</div></div>
 {def&&<aside><div className="panel-header"><div><span className="eyebrow">{patterns.includes(selected)?'CORE QUEST':'EXPANSION QUEST'}</span><h2>{node.label}</h2><small>{node.englishName}</small></div><button onClick={()=>{setEditing(!editing);setDraft(structuredClone(def));}}>{editing?'취소':'조건 편집'}</button></div><div className="panel-body"><span className={'status-pill '+state}>{marks[state]} {names[state]}</span><label className="assignment"><input type="checkbox" checked={assigned} disabled={disabled} onChange={e=>change(q=>{const m=q.members.find(m=>m.id===member.id);m.assigned=e.target.checked?[...m.assigned,selected]:m.assigned.filter(id=>id!==selected)})}/> 이 회원의 학습 목표에 포함</label>
 {editing?<><p className="hint">조건 변경은 테스트 회원 모두에게 적용됩니다. 체크 기록은 회원별로 구분됩니다.</p>{draft.criteria.map((c,i)=><div className="criterion-editor" key={c.id}><input aria-label={'조건 '+(i+1)} value={c.label} onChange={e=>setDraft({...draft,criteria:draft.criteria.map(x=>x.id===c.id?{...x,label:e.target.value}:x)})}/><label><input type="checkbox" checked={c.required} onChange={e=>setDraft({...draft,criteria:draft.criteria.map(x=>x.id===c.id?{...x,required:e.target.checked}:x)})}/>필수</label><button aria-label={'조건 '+(i+1)+' 삭제'} onClick={()=>setDraft({...draft,criteria:draft.criteria.filter(x=>x.id!==c.id)})}>×</button></div>)}<button onClick={()=>setDraft({...draft,criteria:[...draft.criteria,{id:crypto.randomUUID(),label:'',required:true}]})}>＋ 조건 추가</button><h3>선행 퀘스트</h3><div className="prerequisite-list">{Object.keys(q.definitions).filter(id=>id!==selected).map(id=><label key={id}><input type="checkbox" checked={draft.prerequisites.includes(id)} onChange={e=>setDraft({...draft,prerequisites:e.target.checked?[...draft.prerequisites,id]:draft.prerequisites.filter(p=>p!==id)})}/>{doc.nodes.find(n=>n.id===id)?.label}</label>)}</div></>:<>{blocked.length>0&&<div className="lock-note"><b>{rec.override?'코치가 직접 열었습니다':'먼저 달성할 퀘스트'}</b>{blocked.map(id=><button key={id} onClick={()=>{setFilter(q.definitions[id].pattern);select(id)}}>{doc.nodes.find(n=>n.id===id)?.label} →</button>)}<button disabled={disabled||state==='done'} onClick={()=>patchRecord({override:!rec.override})}>{rec.override?'직접 열기 해제':'코치가 직접 열기'}</button></div>}<h3>달성 조건 <span>{req.checked}/{req.total} 필수 완료</span></h3><div className="criteria">{def.criteria.map(c=><label key={c.id}><input type="checkbox" checked={!!rec.checks?.[c.id]} disabled={disabled||state==='locked'||state==='done'||state==='review'} onChange={e=>patchRecord({checks:{...rec.checks,[c.id]:e.target.checked},status:'active'})}/><span>{c.label}<small>{c.required?'필수':'선택'}</small></span></label>)}</div><div className="date-grid"><div>최초 달성일<strong>{date(rec.firstAchievedAt)}</strong></div><div>최근 확인일<strong>{date(rec.lastCheckedAt)}</strong></div></div><label className="memo">코치 메모<textarea placeholder="이번에 확인한 점, 다음 연습 목표…" value={rec.note||''} disabled={disabled} onChange={e=>patchRecord({note:e.target.value})}/></label>{rec.history?.length>0&&<details><summary>달성 기록 {rec.history.length}회</summary>{rec.history.map((h,i)=><p key={i}>{date(h.at)} · {h.action}</p>)}</details>}</>}
 </div><footer className="panel-footer">{editing?<button className="primary" disabled={disabled||JSON.stringify(draft)===JSON.stringify(def)} onClick={saveDefinition}>조건 저장</button>:state==='done'?<button disabled={disabled} onClick={()=>patchRecord({status:'review'})}>↻ 재점검으로 변경</button>:state==='review'?<button className="primary" disabled={disabled} onClick={()=>patchRecord({status:'active'})}>재점검 시작 · 달성일 보존</button>:<><button disabled={disabled||state==='locked'||!assigned||req.checked!==req.total||state==='ready'} onClick={()=>patchRecord({status:'ready'})}>확인 대기</button><button className="primary" disabled={disabled||state==='locked'||!assigned||req.checked!==req.total} onClick={()=>{try{const next=complete(q,member,selected);patchRecord(next);setMessage('✦ 퀘스트 달성! 새로운 움직임으로 확장해 보세요.')}catch(e){setMessage(e.message)}}}>코치 확인 · 달성</button></>}</footer></aside>}
 </main>{message&&<div className="toast" role="status">{message}</div>}</div>
}
createRoot(document.getElementById('root')).render(<ReactFlowProvider><App/></ReactFlowProvider>);
