export const TEST_KEY='640122aa-9d3d-4ec0-af7c-c7d4a17f7f25';
export const patterns=['push','pull','squat','hinge','lunge'];
const examples={push:['pack-ex-chest_press','pack-ex-shoulder_press','pack-ex-db_chest_press'],pull:['pack-ex-seated_row','pack-ex-lat_pulldown','pack-ex-db_row'],squat:['pack-ex-squat_basic','pack-ex-back_squat','pack-ex-hack_squat'],hinge:['pack-ex-romanian_deadlift','pack-ex-hip_thrust','pack-ex-back_extension'],lunge:['pack-ex-split_squat','pack-ex-forward_lunge','pack-ex-side_lunge']};
const cues={push:'밀어내는 동안 손과 팔꿈치의 경로를 설명하고 수행한다',pull:'당기는 동안 팔꿈치의 경로와 몸통 자세를 유지한다',squat:'정한 깊이까지 앉고 일어나며 발의 지지를 유지한다',hinge:'고관절을 접었다 펴면서 정한 몸통 자세를 유지한다',lunge:'분할 또는 이동 자세에서 지지와 균형을 조절한다'};
export function createQuest(doc){let definitions={};for(const p of patterns){definitions[p]={id:p,pattern:p,prerequisites:[],criteria:[{id:p+'-movement',label:cues[p],required:true},{id:p+'-control',label:'코치와 정한 범위에서 돌아오는 구간을 조절한다',required:true},{id:p+'-explain',label:'다른 운동에서도 같은 움직임을 찾아 설명한다',required:false}]};for(const id of examples[p])if(doc.nodes.some(n=>n.id===id))definitions[id]={id,pattern:p,prerequisites:[p],criteria:[{id:id+'-setup',label:'도구와 시작 자세를 스스로 설정한다',required:true},{id:id+'-motion',label:'이 운동에서 합의한 움직임 조건을 수행한다',required:true},{id:id+'-name',label:'영문 이름에서 도구와 동작을 구분한다',required:false}]};}return {schema:1,title:'Movement Quest',definitions,members:[{id:'demo-a',name:'테스트 회원 A',assigned:Object.keys(definitions),records:{}},{id:'demo-b',name:'테스트 회원 B',assigned:Object.keys(definitions),records:{}}]};}
export function record(member,id){return member.records[id]||{checks:{},status:'todo',note:''};}
export function gate(quest,member,id){return (quest.definitions[id]?.prerequisites||[]).filter(p=>record(member,p).status!=='done');}
export function requirements(quest,member,id){const r=record(member,id);const required=quest.definitions[id].criteria.filter(c=>c.required);return {total:required.length,checked:required.filter(c=>r.checks[c.id]).length};}
export function status(quest,member,id){const r=record(member,id);if(r.status==='done'||r.status==='review')return r.status;if(gate(quest,member,id).length&&!r.override)return 'locked';if(r.status==='ready')return 'ready';return r.status==='active'||Object.values(r.checks).some(Boolean)?'active':'todo';}
export function complete(quest,member,id,now=new Date().toISOString()){const r=record(member,id),count=requirements(quest,member,id);if((gate(quest,member,id).length&&!r.override)||count.checked!==count.total||!member.assigned.includes(id))throw Error('필수 조건과 선행 퀘스트를 먼저 확인해 주세요.');return {...r,status:'done',firstAchievedAt:r.firstAchievedAt||now,lastCheckedAt:now,history:[...(r.history||[]),{at:now,action:'달성 확인'}]};}
export function stats(quest,member){const ids=member.assigned.filter(id=>quest.definitions[id]);const done=ids.filter(id=>record(member,id).status==='done').length;return {total:ids.length,done,percent:ids.length?Math.round(done/ids.length*100):0};}
export function validPrerequisites(definitions,id,parents){if(parents.some(p=>!definitions[p]))return false;const next={...definitions,[id]:{...definitions[id],prerequisites:parents}};function visit(key,path){if(path.has(key))return false;const seen=new Set(path);seen.add(key);return (next[key].prerequisites||[]).every(p=>visit(p,seen));}return Object.keys(next).every(k=>visit(k,new Set()));}
