import React,{useState,useEffect,useMemo,useRef,useCallback} from 'react';
import {createRoot} from 'react-dom/client';
import {ReactFlow,ReactFlowProvider,Handle,Position,useReactFlow,Background} from '@xyflow/react';
import {ArrowUpRight,ArrowLeft,ArrowDown,Plus,Minus,Maximize,Focus,Settings,PenLine,Presentation,Undo2,X,ChevronRight,ChevronDown,ImagePlus,Search,Trash2,Upload,Download,Link,RefreshCw,Check,Cloud,CloudOff,GitBranch,Dumbbell,MoveUp,MoveDown,BookOpen,Eye,EyeOff,Copy,FolderPlus} from 'lucide-react';
import {seed,item,themes,pathTo,layout,descendants,deleteBranch,moveNode} from './model';
import {workspace,uid,imageURL,localImage,shrinkImage,writeLocal} from './storage';
import {applyContentPack,pack} from './content-pack';
import {useDocument} from './useDocument';
import {exportBackup,importBackup} from './backup';
import '@xyflow/react/dist/style.css';
import './style.css';
const key=workspace();
function IconButton({title,children,...props}){return <button className="icon-btn" title={title} aria-label={title} {...props}>{children}</button>}
function Photo({url,...props}){let [src,setSrc]=useState(''),[failed,setFailed]=useState(false);useEffect(()=>{let live=true;setFailed(false);imageURL(url).then(s=>{if(live)setSrc(s)});return()=>{live=false}},[url]);return src&&!failed?<img src={src} {...props} onError={()=>setFailed(true)}/>:<div className="photo-fallback"><ImagePlus size={22}/><span>{failed?'이미지 연결 확인':'이미지'}</span></div>}
function Card({data}){let {node:n,count,open,selected}=data;return <div className={'tree-card '+(!n.parent?'root-card ':'')+(selected?'selected ':'')+(n.show?.image!==false&&n.images.length?'has-image ':'')+(n.englishName?.trim()?'has-english':'')}>
 <Handle type="target" position={Position.Top}/>
 <div className="card-top"><span className="micro">{!n.parent?'시작하기':n.kind==='exercise'?'EXERCISE':'MOVEMENT'}</span>{n.kind==='exercise'?<Dumbbell size={17}/>:<GitBranch size={16}/>}</div>
 {n.show?.image!==false&&n.images[0]?<Photo url={n.images[0].url} className="card-photo" alt={n.label}/>:null}
 <div className="card-name">{n.label}</div>
 {n.englishName?.trim()&&<div className="card-english" title={n.englishName}>{n.englishName}</div>}
 <div className="card-bottom"><span>{count?`${count}개의 가지`:n.kind==='exercise'?'운동 살펴보기':'이 움직임 알아보기'}</span><span className="node-action">{count?(open?<Minus size={15}/>:<Plus size={15}/>):<ArrowUpRight size={15}/>}</span></div>
 <Handle type="source" position={Position.Bottom}/>
 </div>}
const nodeTypes={movement:Card};
function Modal({title,onClose,children,wide=false}){return <div className="modal-backdrop" onClick={onClose}><section role="dialog" aria-modal="true" aria-label={title} className={'modal '+(wide?'wide':'')} onClick={e=>e.stopPropagation()}><header><h2>{title}</h2><IconButton title="닫기" onClick={onClose}><X/></IconButton></header>{children}</section></div>}
function App(){
 const [showIntro,setShowIntro]=useState(false),[focusMode,setFocusMode]=useState(false);
 const sync=useDocument(key),{doc,replace,ready,status}=sync;
 const [expanded,setExpanded]=useState(new Set()),[selected,setSelected]=useState(null),[editing,setEditing]=useState(false),[panel,setPanel]=useState(false),[settings,setSettings]=useState(false),[picker,setPicker]=useState(null),[query,setQuery]=useState(''),[images,setImages]=useState([]),[inputs,setInputs]=useState([]),[limit,setLimit]=useState(36),[toast,setToast]=useState(''),[working,setWorking]=useState(false),[history,setHistory]=useState([]),[confirm,setConfirm]=useState(null),[newItem,setNewItem]=useState(null),[newLabel,setNewLabel]=useState(''),[search,setSearch]=useState('');
 const flow=useReactFlow(),fileRef=useRef(),restoreRef=useRef(),isMoving=useRef(false);
 const notify=t=>{setToast(t);setTimeout(()=>setToast(''),4500)};
 useEffect(()=>{fetch(import.meta.env.BASE_URL+'images.json').then(r=>r.json()).then(setImages).catch(()=>notify('이미지 목록을 불러오지 못했습니다.'));fetch(import.meta.env.BASE_URL+'exercises.json').then(r=>r.json()).then(setInputs).catch(()=>notify('운동 목록을 불러오지 못했습니다.'))},[]);
 useEffect(()=>{if(sync.error)notify(sync.error)},[sync.error]);
 const currentDoc=useRef(doc);currentDoc.current=doc;
 const packAttempted=useRef(false);
 useEffect(()=>{if(!ready||sync.conflict||doc.contentPacks?.includes(pack.id)||packAttempted.current)return;packAttempted.current=true;(async()=>{try{await writeLocal(key+':before-'+pack.id,{doc:structuredClone(currentDoc.current),revision:null,dirty:false});replace(applyContentPack(currentDoc.current));notify('하체 분류를 수정했습니다. 기존 사진과 작성한 설명은 유지됩니다.')}catch(e){notify('운동 자료를 추가하지 못했습니다: '+e.message)}})()},[ready,doc,sync.conflict]);
 const change=fn=>{try{let before=structuredClone(currentDoc.current),next=fn(structuredClone(currentDoc.current));replace(next);currentDoc.current=next;setHistory(h=>[...h.slice(-29),before])}catch(e){notify(e.message)}};
 const patch=(id,values)=>change(d=>{let n=d.nodes.find(n=>n.id===id);if(n)Object.assign(n,typeof values==='function'?values(n):values);return d});
 const node=doc.nodes.find(n=>n.id===selected),theme=themes[doc.theme]||themes.green;
 const rows=useMemo(()=>layout(doc,expanded),[doc,expanded]);
 const canvasNodes=rows.map(n=>({id:n.id,type:'movement',position:n.position,data:{node:n,count:doc.nodes.filter(x=>x.parent===n.id).length,open:expanded.has(n.id),selected:n.id===selected},draggable:false}));
 const visible=new Set(rows.map(n=>n.id));
 const edges=[...rows.filter(n=>n.parent&&visible.has(n.parent)).map(n=>({id:'parent-'+n.id,source:n.parent,target:n.id,type:'smoothstep',pathOptions:{offset:10,centerY:n.position.y-22},style:{stroke:theme.color,strokeWidth:2,opacity:.65,...(n.relation==='related'?{strokeDasharray:'6 6'}:{})}})),...doc.links.filter(l=>visible.has(l.source)&&visible.has(l.target)).map(l=>({...l,type:'smoothstep',style:{stroke:theme.color,strokeWidth:2,strokeDasharray:'6 6'}}))];
 const topology=rows.map(n=>n.id+':'+n.position.y+':'+(n.show?.image!==false&&n.images.length>0)).join('|');
 useEffect(()=>{let timer=setTimeout(()=>{if(!isMoving.current)flow.fitView({padding:.22,maxZoom:1,minZoom:.04,duration:420})},160);return()=>clearTimeout(timer)},[topology,panel,showIntro,focusMode]);
 const toggle=n=>{setSelected(n.id);let kids=doc.nodes.some(x=>x.parent===n.id);if(kids)setExpanded(s=>{let t=new Set(s);t.has(n.id)?t.delete(n.id):t.add(n.id);return t});if(editing||!kids){setPanel(true)}};
 const focus=id=>{let next=new Set(expanded);for(let p of pathTo(doc,id).slice(0,-1))next.add(p.id);setExpanded(next);setSelected(id);setPanel(true);setSearch('')};
 const add=(label,parent,kind='branch')=>{if(!label.trim())return;let n=item(uid(),label.trim(),parent,kind);change(d=>{d.nodes.push(n);return d});if(parent)setExpanded(s=>new Set([...s,parent]));setSelected(n.id);setPanel(true);setNewItem(null);setNewLabel('');return n.id};
 const setShown=(field,value)=>patch(node.id,{show:{...node.show,[field]:value}});
 const chooseImage=image=>{patch(node.id,{images:[...node.images,{id:uid(),url:image.url,alt:image.name}]});setPicker(null);setQuery('')};
 const upload=async e=>{let files=[...e.target.files];e.target.value='';if(!node||!files.length)return;setWorking(true);try{let additions=[];for(let f of files){let url=await localImage(await shrinkImage(f));additions.push({id:uid(),url,alt:f.name})}patch(node.id,n=>({images:[...n.images,...additions]}))}catch(e){notify(e.message)}finally{setWorking(false)}};
 const reorder=(direction)=>change(d=>{let n=d.nodes.find(n=>n.id===selected);let siblings=d.nodes.filter(x=>x.parent===n.parent);let i=siblings.findIndex(x=>x.id===n.id);let other=siblings[i+direction];if(other){let a=d.nodes.indexOf(n),b=d.nodes.indexOf(other);[d.nodes[a],d.nodes[b]]=[d.nodes[b],d.nodes[a]]}return d});
 const statusLabels={loading:'불러오는 중',pending:'저장 대기',saving:'동기화 중',saved:'클라우드 저장됨',offline:'기기에 저장 · 연결 대기',setup:'기기에 저장 · 클라우드 미연결',conflict:'동시 수정 확인 필요'};
 const normalize=s=>s.toLowerCase().replace(/\s+/g,'');
 const candidates=(picker==='images'?images:inputs).filter(r=>normalize(r.name).includes(normalize(query)));
 return <div className={"app compact-app"+(focusMode?" focus-mode":"")} style={{'--accent':theme.color,'--tint':theme.color+'0d','--line':theme.color+'40'}}>
 <header className="app-header"><div className="brand"><span className="brand-mark"><GitBranch size={24}/></span><div><strong>MOVEMENT <span>ATLAS</span></strong><small>VERA GYM · 움직임을 이해하는 지도</small></div></div><div className="header-actions"><span className={'save-status '+(status==='saved'?'ok':'')} title={statusLabels[status]}>{status==='saved'?<Check size={14}/>:status==='saving'?<RefreshCw size={14}/>:<CloudOff size={14}/>}<span>{statusLabels[status]}</span></span><div className="mode-switch"><button className={!editing?'active':''} onClick={()=>{setEditing(false);setPanel(false)}}><Presentation size={16}/><span>상담</span></button><button disabled={!ready} className={editing?'active':''} onClick={()=>setEditing(true)}><PenLine size={16}/><span>편집</span></button></div><IconButton title={showIntro?"안내 접기":"안내 펼치기"} onClick={()=>setShowIntro(v=>!v)}><BookOpen size={19}/></IconButton><IconButton title="설정" onClick={()=>setSettings(true)}><Settings size={21}/></IconButton></div></header>
 {showIntro&&<section className="page-heading"><div><p className="eyebrow">LEARN THE MOVEMENT. EXPLORE THE POSSIBILITIES.</p><h1>하나의 움직임에서, <span>다양한 운동으로.</span></h1><p className="intro">가지를 눌러 펼쳐보세요. 도구가 달라져도, 배운 움직임은 이어집니다.</p></div><div className="heading-aside"><span><b>{doc.nodes.filter(n=>n.kind==='exercise').length}</b> 운동</span><span><b>{doc.nodes.filter(n=>n.kind==='branch').length}</b> 가지</span></div></section>}
 <div className="workspace-toolbar"><div className="trail"><span className="live-dot"/> {editing?'나만의 운동 지도를 편집하세요':'움직임을 선택해 시작하세요'}<span className="divider"/><span className="muted">{rows.length}개 펼쳐짐</span></div><div className="tools"><IconButton title="트리 집중 보기" onClick={()=>setFocusMode(true)}><Maximize size={18}/></IconButton><div className="search-wrap"><Search size={16}/><input aria-label="트리에서 운동 찾기" placeholder="트리에서 찾기" value={search} onChange={e=>setSearch(e.target.value)}/>{search&&<div className="search-results">{doc.nodes.filter(n=>[n.label,n.englishName||''].some(text=>normalize(text).includes(normalize(search)))).slice(0,15).map(n=><button key={n.id} onClick={()=>focus(n.id)}>{n.label}{n.englishName?.trim()&&<small>{n.englishName}</small>}<small>{pathTo(doc,n.id).slice(0,-1).map(n=>n.label).join(' › ')}</small></button>)}</div>}</div>{editing&&<><IconButton title="실행 취소" disabled={!history.length} onClick={()=>{replace(history.at(-1));setHistory(h=>h.slice(0,-1));setSelected(null);setPanel(false)}}><Undo2 size={18}/></IconButton><button className="btn accent" onClick={()=>{setNewItem({parent:selected||null});setNewLabel('')}}><Plus size={17}/>가지 추가</button></>}</div></div>
 <main className="main"><div className="canvas">{focusMode&&<button className="focus-exit btn" onClick={()=>setFocusMode(false)}><X size={17}/>집중 보기 종료</button>}<ReactFlow nodes={canvasNodes} edges={edges} nodeTypes={nodeTypes} onNodeClick={(_,n)=>toggle(n.data.node)} nodesDraggable={false} nodesConnectable={false} elementsSelectable={false} minZoom={.04} maxZoom={2.5} zoomOnDoubleClick={false} zoomOnPinch panOnDrag onMoveStart={e=>{if(e)isMoving.current=true}} onMoveEnd={()=>{isMoving.current=false}} fitView fitViewOptions={{maxZoom:1,padding:.25}}>
 <Background color="#d9e0dd" gap={24} size={1}/>
 </ReactFlow><div className="canvas-legend"><span><i/>움직임 확장</span><span><i className="dashed"/>관련 보조운동</span></div><div className="viewport-controls"><IconButton title="확대" onClick={()=>flow.zoomIn({duration:200})}><Plus size={20}/></IconButton><IconButton title="축소" onClick={()=>flow.zoomOut({duration:200})}><Minus size={20}/></IconButton><span/><IconButton title="전체 보기" onClick={()=>flow.fitView({padding:.22,maxZoom:1,duration:400})}><Maximize size={19}/></IconButton><IconButton title="선택 가지 보기" disabled={!selected} onClick={()=>{let ids=descendants(doc,selected);flow.fitView({nodes:canvasNodes.filter(n=>ids.has(n.id)),padding:.2,maxZoom:1.25,duration:400})}}><Focus size={19}/></IconButton></div><div className="gesture-hint">드래그로 이동 · 두 손가락으로 확대</div></div>
 {panel&&node&&<aside className="inspector"><div className="inspector-header"><span className="eyebrow">{editing?'EDIT YOUR MOVEMENT':'EXPLORE THE MOVEMENT'}</span><IconButton title="상세 닫기" onClick={()=>setPanel(false)}><X size={20}/></IconButton></div><div className="inspector-body">
 {editing?<label className="field-label">이름 <span className="required">필수</span><input key={'name'+node.id} defaultValue={node.label} maxLength={200} onBlur={e=>{let v=e.target.value.trim();if(v&&v!==node.label)patch(node.id,{label:v});else e.target.value=node.label}} onKeyDown={e=>{if(e.key==='Enter')e.target.blur()}}/></label>:<h2 className="detail-title">{node.label}</h2>}
 {editing?<label className="field-label">영문 이름<input aria-label="영문 이름" key={'english'+node.id} defaultValue={node.englishName||''} maxLength={200} placeholder="예: Incline Chest Press" onBlur={e=>{const value=e.target.value.trim();if(value!==(node.englishName||''))patch(node.id,{englishName:value});e.target.value=value}} onKeyDown={e=>{if(e.key==='Enter')e.target.blur()}}/><small className="english-hint">비워두면 표시하지 않습니다.</small></label>:node.englishName?.trim()?<p className="detail-english">{node.englishName}</p>:null}
 {(editing||node.show?.image!==false)&&<section className="detail-section">{editing&&<div className="section-label"><h3>이미지</h3><IconButton title={node.show?.image===false?'이미지 보이기':'이미지 숨기기'} onClick={()=>setShown('image',node.show?.image===false)}>{node.show?.image===false?<EyeOff size={16}/>:<Eye size={16}/>}</IconButton></div>}{node.images.length?<div className="detail-images">{node.images.map((im,i)=><div className="detail-image" key={im.id}><Photo url={im.url} alt={im.alt||node.label}/>{editing&&<div className="image-actions"><span>{i===0?'대표 이미지':`${i+1}번째`}</span><IconButton title="이미지 앞으로" disabled={i===0} onClick={()=>{let imgs=[...node.images];[imgs[i-1],imgs[i]]=[imgs[i],imgs[i-1]];patch(node.id,{images:imgs})}}><MoveUp size={15}/></IconButton><IconButton title="이미지 연결 제거" onClick={()=>patch(node.id,{images:node.images.filter(x=>x.id!==im.id)})}><X size={15}/></IconButton></div>}</div>)}</div>:editing?<div className="empty-photo"><ImagePlus size={28}/><p>이 움직임을 보여주는 이미지</p><small>이미지는 나중에 추가해도 괜찮아요.</small></div>:null}{editing&&<div className="button-row"><button className="btn" onClick={()=>{setPicker('images');setQuery('');setLimit(36)}}><Search size={16}/>기존 이미지</button><button className="btn" disabled={working} onClick={()=>fileRef.current.click()}><Upload size={16}/>사진 추가</button></div>}</section>}
 {(editing||node.show?.path!==false)&&<section className="detail-section"><div className="section-label"><h3>소속 가지</h3>{editing&&<IconButton title="소속 경로 표시 전환" onClick={()=>setShown('path',node.show?.path===false)}>{node.show?.path===false?<EyeOff size={16}/>:<Eye size={16}/>}</IconButton>}</div><div className="breadcrumbs">{pathTo(doc,node.id).map((n,i)=><React.Fragment key={n.id}>{i>0&&<ChevronRight size={13}/>}<button className={n.id===node.id?'current':''} onClick={()=>focus(n.id)}>{n.label}</button></React.Fragment>)}</div>{editing&&<label className="field-label small">다른 가지로 이동<select value={node.parent||''} onChange={e=>change(d=>moveNode(d,node.id,e.target.value||null))}><option value="">최상위</option>{doc.nodes.filter(n=>!descendants(doc,node.id).has(n.id)).map(n=><option key={n.id} value={n.id}>{pathTo(doc,n.id).map(n=>n.label).join(' › ')}</option>)}</select></label>}</section>}
 {(editing||node.show?.meanings!==false&&node.meanings.some(m=>m.word||m.meaning))&&<section className="detail-section"><div className="section-label"><h3>운동 이름 풀이</h3>{editing&&<IconButton title="이름 풀이 표시 전환" onClick={()=>setShown('meanings',node.show?.meanings===false)}>{node.show?.meanings===false?<EyeOff size={16}/>:<Eye size={16}/>}</IconButton>}</div>{node.meanings.map((m,i)=>editing?<div className="meaning-editor" key={m.id}><input aria-label="풀이 단어" placeholder="예: Incline" value={m.word} onChange={e=>patch(node.id,{meanings:node.meanings.map(x=>x.id===m.id?{...x,word:e.target.value}:x)})}/><span>=</span><input aria-label="단어 뜻" placeholder="예: 상향 경사" value={m.meaning} onChange={e=>patch(node.id,{meanings:node.meanings.map(x=>x.id===m.id?{...x,meaning:e.target.value}:x)})}/><IconButton title="풀이 삭제" onClick={()=>patch(node.id,{meanings:node.meanings.filter(x=>x.id!==m.id)})}><X size={14}/></IconButton></div>:m.word||m.meaning?<div className="meaning" key={m.id}><strong>{m.word}</strong><span>{m.meaning}</span></div>:null)}{editing&&<button className="text-btn" onClick={()=>patch(node.id,{meanings:[...node.meanings,{id:uid(),word:'',meaning:''}]})}><Plus size={15}/>단어 추가</button>}</section>}
 {node.fields.filter(f=>editing||f.visible!==false&&f.body.trim()).map(f=><section className="detail-section" key={f.id}>{editing?<><div className="custom-title"><input aria-label="설명 제목" placeholder="예: 이번에 달라지는 점" value={f.title} onChange={e=>patch(node.id,{fields:node.fields.map(x=>x.id===f.id?{...x,title:e.target.value}:x)})}/><IconButton title="설명 표시 전환" onClick={()=>patch(node.id,{fields:node.fields.map(x=>x.id===f.id?{...x,visible:x.visible===false}:x)})}>{f.visible===false?<EyeOff size={16}/>:<Eye size={16}/>}</IconButton><IconButton title="설명 삭제" onClick={()=>patch(node.id,{fields:node.fields.filter(x=>x.id!==f.id)})}><X size={16}/></IconButton></div><textarea aria-label="설명 내용" placeholder="필요한 설명을 자유롭게 적으세요." value={f.body} onChange={e=>patch(node.id,{fields:node.fields.map(x=>x.id===f.id?{...x,body:e.target.value}:x)})}/></>:<><h3>{f.title}</h3><p className="body-copy">{f.body}</p></>}</section>)}
 {editing&&<><button className="btn full" onClick={()=>patch(node.id,{fields:[...node.fields,{id:uid(),title:'',body:'',visible:true}]})}><Plus size={16}/>설명 항목 추가</button><section className="detail-section"><label className="field-label">항목 종류<select value={node.kind} onChange={e=>patch(node.id,{kind:e.target.value})}><option value="branch">분류 가지</option><option value="exercise">운동 열매</option></select></label><div className="button-row"><button className="btn" onClick={()=>{setNewItem({parent:node.id});setNewLabel('')}}><FolderPlus size={16}/>하위 가지</button><button className="btn" onClick={()=>{setPicker('inputs');setQuery('');setLimit(36)}}><BookOpen size={16}/>운동 가져오기</button></div><div className="button-row"><button className="btn" onClick={()=>reorder(-1)}><MoveUp size={16}/>앞으로</button><button className="btn" onClick={()=>reorder(1)}><MoveDown size={16}/>뒤로</button></div></section><section className="detail-section"><h3>관련 보조운동 연결</h3><select aria-label="보조운동 연결" value="" onChange={e=>{if(e.target.value)change(d=>{if(!d.links.some(l=>l.source===node.id&&l.target===e.target.value))d.links.push({id:uid(),source:node.id,target:e.target.value});return d})}}><option value="">점선으로 연결할 항목 선택</option>{doc.nodes.filter(n=>n.id!==node.id).map(n=><option key={n.id} value={n.id}>{n.label}</option>)}</select>{doc.links.filter(l=>l.source===node.id||l.target===node.id).map(l=><div className="related-row" key={l.id}>{doc.nodes.find(n=>n.id===(l.source===node.id?l.target:l.source))?.label}<IconButton title="점선 연결 제거" onClick={()=>change(d=>({...d,links:d.links.filter(x=>x.id!==l.id)}))}><X size={15}/></IconButton></div>)}</section><button className="btn danger full" onClick={()=>setConfirm({title:'가지를 삭제할까요?',body:`‘${node.label}’와 하위 항목 ${descendants(doc,node.id).size-1}개가 함께 삭제됩니다. 이미지 원본 파일은 삭제하지 않습니다.`,action:()=>{change(d=>deleteBranch(d,node.id));setPanel(false);setSelected(null)}})}><Trash2 size={16}/>이 가지 삭제</button></>}
 {!editing&&!node.images.length&&!node.meanings.length&&!node.fields.some(f=>f.visible!==false&&f.body)&&<p className="quiet-note">같은 움직임에서 출발해<br/>도구와 자세의 차이를 배워보세요.</p>}
 </div></aside>}
 </main><footer className="app-footer"><span>움직임을 배우면, 어디서든 운동할 수 있습니다.</span><span>VERA GYM <span className="footer-dot">·</span> MOVEMENT EDUCATION</span></footer>
 <input ref={fileRef} type="file" hidden accept="image/jpeg,image/png,image/webp" multiple onChange={upload}/><input ref={restoreRef} type="file" hidden accept=".zip" onChange={async e=>{let f=e.target.files[0];e.target.value='';if(!f)return;setWorking(true);try{let d=await importBackup(f);setConfirm({title:'백업으로 복원할까요?',body:`현재 트리를 백업의 ${d.nodes.length}개 항목으로 바꿉니다. 기존 트리는 실행 취소로 되돌릴 수 있습니다.`,action:()=>{change(()=>d);setSettings(false);setExpanded(new Set());setPanel(false);setSelected(null)}})}catch(e){notify(e.message)}finally{setWorking(false)}}}/>
 {settings&&<Modal title="나만의 지도 설정" onClose={()=>setSettings(false)}><div className="modal-body"><p className="eyebrow">COLOR THE CONNECTIONS</p><h3>일곱 가지 색, 하나의 움직임 지도</h3><p className="muted">배경은 흰색으로, 테두리와 연결선만 바뀝니다.</p><div className="theme-picker">{Object.entries(themes).map(([k,t])=><button key={k} aria-label={t.name+' 테마'} className={k===doc.theme?'chosen':''} onClick={()=>change(d=>({...d,theme:k}))}><span style={{background:t.color}}>{k===doc.theme&&<Check size={19}/>}</span><small>{t.name}</small></button>)}</div><hr/><h3>기기 간 동기화</h3><p className="muted">{statusLabels[status]}<br/>같은 개인 링크를 태블릿에서 열면 이 트리가 이어집니다.</p><div className="button-row"><button className="btn" onClick={async()=>{try{await navigator.clipboard.writeText(location.href);notify('개인 링크를 복사했어요.')}catch{notify('주소창의 링크를 복사해 주세요.')}}}><Copy size={16}/>개인 링크 복사</button><button className="btn" onClick={()=>sync.refresh()}><RefreshCw size={16}/>연결 확인</button></div><small className="quiet-note">개인 링크를 가진 사람은 편집할 수 있습니다.</small>{status==='setup'&&<p className="setup-note">클라우드 연결 준비 중입니다. 지금 편집한 내용은 이 기기에 저장됩니다. Supabase 설정을 적용한 뒤 ‘연결 확인’을 눌러주세요.</p>}<hr/><h3>백업과 복원</h3><p className="muted">트리와 이미지를 함께 ZIP 파일로 보관합니다.</p><div className="button-row"><button className="btn" disabled={working} onClick={async()=>{setWorking(true);try{await exportBackup(doc);notify('백업을 내보냈어요.')}catch(e){notify(e.message)}finally{setWorking(false)}}}><Download size={16}/>{working?'처리 중…':'백업 내보내기'}</button><button className="btn" disabled={working} onClick={()=>restoreRef.current.click()}><Upload size={16}/>백업 불러오기</button></div></div></Modal>}
 {picker&&node&&<Modal title={picker==='images'?'운동 이미지 라이브러리':'기초 운동 목록에서 가져오기'} onClose={()=>setPicker(null)} wide><div className="modal-body"><p className="muted">{picker==='images'?'기존 이미지를 연결합니다. 원본 파일은 그대로 유지됩니다.':'57개 운동 이름만 가져옵니다. 원본 자료의 분류 구조는 적용하지 않습니다.'}</p><div className="library-search"><Search size={18}/><input autoFocus aria-label="라이브러리 검색" placeholder="운동 이름으로 검색" value={query} onChange={e=>{setQuery(e.target.value);setLimit(36)}}/><span>{candidates.length}개</span></div><div className={picker==='images'?'image-grid':'input-list'}>{candidates.slice(0,limit).map(r=><button key={r.id} onClick={()=>{if(picker==='images')chooseImage(r);else{add(r.name,node.id,'exercise');setPicker(null)}}}>{picker==='images'&&<Photo url={r.url} alt={r.name} loading="lazy"/>}<span>{r.name}</span>{picker==='inputs'&&<Plus size={17}/>}</button>)}</div>{!candidates.length&&<p className="empty-state">검색 결과가 없습니다.</p>}{candidates.length>limit&&<button className="btn full" onClick={()=>setLimit(v=>v+36)}>더 보기</button>}</div></Modal>}
 {newItem&&<Modal title="새 가지 만들기" onClose={()=>setNewItem(null)}><form className="modal-body" onSubmit={e=>{e.preventDefault();add(newLabel,newItem.parent)}}><label className="field-label">이름<input autoFocus value={newLabel} maxLength={200} onChange={e=>setNewLabel(e.target.value)} placeholder="예: 체스트 프레스"/></label><p className="muted">소속: {newItem.parent?pathTo(doc,newItem.parent).map(n=>n.label).join(' › '):'최상위'}</p><button className="btn accent full" disabled={!newLabel.trim()}>가지 추가</button></form></Modal>}
 {confirm&&<Modal title={confirm.title} onClose={()=>setConfirm(null)}><div className="modal-body"><p>{confirm.body}</p><div className="button-row"><button className="btn" onClick={()=>setConfirm(null)}>취소</button><button className="btn accent" onClick={()=>{confirm.action();setConfirm(null)}}>확인</button></div></div></Modal>}
 {sync.conflict&&<Modal title="다른 기기에서도 수정했어요" onClose={()=>{}}><div className="modal-body"><p>내용을 자동으로 덮어쓰지 않았습니다. 먼저 이 기기 내용을 백업한 뒤 사용할 버전을 선택해 주세요.</p><button className="btn full" onClick={()=>exportBackup(doc).catch(e=>notify(e.message))}><Download size={16}/>이 기기 버전 백업</button><div className="button-row"><button className="btn" disabled={!sync.conflict.document} onClick={()=>sync.resolve('remote')}>서버 버전 사용</button><button className="btn accent" disabled={!sync.conflict.document} onClick={()=>sync.resolve('local')}>이 기기 버전으로 저장</button></div>{!sync.conflict.document&&<button className="btn" onClick={()=>sync.refresh()}>다시 확인</button>}</div></Modal>}
 {toast&&<div role="status" className="toast">{toast}</div>}
 </div>;
}
createRoot(document.getElementById('root')).render(<ReactFlowProvider><App/></ReactFlowProvider>);





