export const themes={red:{name:'빨강',color:'#b72e3c'},orange:{name:'주황',color:'#b95a17'},yellow:{name:'노랑',color:'#937009'},green:{name:'초록',color:'#08735b'},blue:{name:'파랑',color:'#2860bb'},indigo:{name:'남색',color:'#3c428c'},purple:{name:'보라',color:'#8050ae'}};
export function item(id,label,parent=null,kind='branch'){return {id,label,parent,kind,images:[],meanings:[],fields:[],show:{image:true,path:true,meanings:true}}}
export function seed(){return {version:1,theme:'green',nodes:[item('upper','상체'),item('lower','하체'),item('push','밀기','upper'),item('pull','당기기','upper'),item('squat','스쿼트','lower'),item('hinge','힌지','lower'),item('lunge','런지','lower'),item('press','프레스','push'),item('row','로우','pull'),item('pulldown','풀다운','pull'),item('machine','머신','row'),item('cable','케이블','row'),item('dumbbell','덤벨','row'),item('barbell','바벨','row')],links:[]}}
export function descendants(doc,id){let out=new Set([id]);for(let changed=true;changed;){changed=false;for(const n of doc.nodes)if(out.has(n.parent)&&!out.has(n.id)){out.add(n.id);changed=true}}return out}
export function pathTo(doc,id){const map=new Map(doc.nodes.map(n=>[n.id,n])),out=[],seen=new Set();while(id&&map.has(id)&&!seen.has(id)){seen.add(id);let n=map.get(id);out.unshift(n);id=n.parent}return out}
export function validateDoc(d){
 if(!d||d.version!==1||!Array.isArray(d.nodes)||!d.nodes.length||d.nodes.length>3000||!themes[d.theme])throw Error('유효한 트리 백업이 아닙니다.');
 const ids=new Set();for(const n of d.nodes){if(typeof n.id!=='string'||!n.id||ids.has(n.id)||typeof n.label!=='string'||!n.label.trim()||n.label.length>200||!['branch','exercise'].includes(n.kind))throw Error('이름 또는 ID가 올바르지 않습니다.');ids.add(n.id);if(!Array.isArray(n.images)||!Array.isArray(n.meanings)||!Array.isArray(n.fields))throw Error('항목 형식이 올바르지 않습니다.');for(const im of n.images)if(typeof im.url!=='string'||!(/^(https?:\/\/|local:)/.test(im.url)))throw Error('허용되지 않는 이미지 주소입니다.');for(const m of n.meanings)if(typeof m.word!=='string'||typeof m.meaning!=='string')throw Error('이름 풀이 형식 오류');for(const f of n.fields)if(typeof f.title!=='string'||typeof f.body!=='string')throw Error('설명 형식 오류');}
 for(const n of d.nodes){if(n.parent!==null&&!ids.has(n.parent))throw Error('소속 가지가 없습니다.');let p=n.id,seen=new Set();while(p){if(seen.has(p))throw Error('가지가 순환 연결되어 있습니다.');seen.add(p);p=d.nodes.find(x=>x.id===p)?.parent}}
 if(!Array.isArray(d.links)||d.links.some(l=>!ids.has(l.source)||!ids.has(l.target)||l.source===l.target))throw Error('보조운동 연결이 올바르지 않습니다.');return d;
}
export function moveNode(doc,id,parent){if(parent&&descendants(doc,id).has(parent))throw Error('자기 자신이나 하위 가지로 옮길 수 없습니다.');let d=structuredClone(doc);d.nodes.find(n=>n.id===id).parent=parent;return validateDoc(d)}
export function deleteBranch(doc,id){let gone=descendants(doc,id);let d={...doc,nodes:doc.nodes.filter(n=>!gone.has(n.id)),links:doc.links.filter(l=>!gone.has(l.source)&&!gone.has(l.target))};return validateDoc(d)}
export function visibleNodes(doc,expanded){return doc.nodes.filter(n=>pathTo(doc,n.id).slice(0,-1).every(p=>expanded.has(p.id)))}
export function layout(doc,expanded){let visible=visibleNodes(doc,expanded),out=[],cursor=0;const walk=(n,depth)=>{let kids=visible.filter(x=>x.parent===n.id);let start=cursor;let centers=kids.map(k=>walk(k,depth+1));if(!kids.length)cursor+=270;let x=kids.length?(centers[0]+centers.at(-1))/2:start;out.push({...n,position:{x,y:depth*220},depth});return x};for(const n of visible.filter(n=>!n.parent)){walk(n,0);cursor+=50}let y=0;for(let depth=0;depth<=Math.max(...out.map(n=>n.depth));depth++){let row=out.filter(n=>n.depth===depth);for(let n of row)n.position.y=y;y+=Math.max(...row.map(n=>n.show?.image!==false&&n.images.length?312:176))+44}return out}

