import {get,set} from 'idb-keyval';
import config from './config.json';
export const uid=()=>crypto.randomUUID();
export function workspace(){let h=new URLSearchParams(location.hash.slice(1)).get('tree');let saved=localStorage.getItem('mt-last');let key=/^[\da-f]{8}(-[\da-f]{4}){3}-[\da-f]{12}$/i.test(h||'')?h:saved||uid();location.hash=new URLSearchParams({tree:key}).toString();localStorage.setItem('mt-last',key);return key}
export const readLocal=k=>get('tree:'+k);
export const writeLocal=(k,data)=>set('tree:'+k,data);
export async function rpc(name,args){let r;try{r=await fetch(config.url+'/rest/v1/rpc/'+name,{method:'POST',headers:{apikey:config.anon,Authorization:'Bearer '+config.anon,'Content-Type':'application/json'},body:JSON.stringify(args),signal:AbortSignal.timeout(15000)})}catch{throw Error('OFFLINE')}let data=await r.json();if(!r.ok){if(data.code==='40001')throw Error('CONFLICT');if(r.status===404||data.code==='PGRST202')throw Error('SETUP');throw Error(data.message||'서버에 저장하지 못했습니다.')}return data}
export async function localImage(blob){let id=uid();await set('image:'+id,blob);return 'local:'+id}
const urls=new Map();
export async function imageURL(url){if(!url?.startsWith('local:'))return url;if(urls.has(url))return urls.get(url);let b=await get('image:'+url.slice(6));if(!b)return '';let u=URL.createObjectURL(b);urls.set(url,u);return u}
export async function imageBlob(url){if(url.startsWith('local:')){let b=await get('image:'+url.slice(6));if(!b)throw Error('이미지 파일이 없습니다.');return b}let r=await fetch(url,{signal:AbortSignal.timeout(20000)});if(!r.ok)throw Error('이미지를 백업하지 못했습니다. 네트워크를 확인해 주세요.');return r.blob()}
export async function uploadImage(key,url){let blob=await imageBlob(url);let ext=blob.type==='image/png'?'png':blob.type==='image/webp'?'webp':'jpg';let path=key+'/'+uid()+'.'+ext;let r=await fetch(config.url+'/storage/v1/object/movement-tree-images/'+path,{method:'POST',headers:{apikey:config.anon,Authorization:'Bearer '+config.anon,'Content-Type':blob.type},body:blob,signal:AbortSignal.timeout(30000)});if(!r.ok)throw Error('이미지 업로드 실패');return config.url+'/storage/v1/object/public/movement-tree-images/'+path}
export async function shrinkImage(file){if(!['image/jpeg','image/png','image/webp'].includes(file.type))throw Error('JPG, PNG, WebP 이미지를 선택해 주세요.');if(file.size>20000000)throw Error('20MB 이하 이미지를 선택해 주세요.');let bmp=await createImageBitmap(file);let ratio=Math.min(1,1600/Math.max(bmp.width,bmp.height));let canvas=document.createElement('canvas');canvas.width=Math.round(bmp.width*ratio);canvas.height=Math.round(bmp.height*ratio);canvas.getContext('2d').drawImage(bmp,0,0,canvas.width,canvas.height);bmp.close();let mime=file.type==='image/png'?'image/png':'image/jpeg';let blob=await new Promise(resolve=>canvas.toBlob(resolve,mime,.82));if(!blob)throw Error('사진을 처리하지 못했습니다.');return blob.size<file.size?blob:file}
